name: Two jobs

on:
  workflow_dispatch:

jobs:
  job1:
    name: Yocto Build Part 1
    runs-on: ubuntu-latest
    steps:
    - run: mkdir -p tmp/work
    - run: mkdir -p ros_common_artifacts/downloads && mkdir -p ros_common_artifacts/sstate-cache-hardknott
    - run: echo hello > tmp/work/world.txt
    - run: echo hello > ros_common_artifacts/downloads/world.txt

    - uses: actions/upload-artifact@v2
      with:
        name: yocto-build-artifacts
        path: |
          tmp
          ros_common_artifacts

  job2:
    name: Yocto Build Part 2
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
      - uses: actions/download-artifact@v2
        with:
          name: yocto-build-artifacts

      - run: cat tmp/work/world.txt
      - run: cat ros_common_artifacts/downloads/world.txt

      - name: Delete artifacts
      - uses: geekyeggo/delete-artifact@v1.0.0
        with:
          name: yocto-build-artifacts
